const router = require('express').Router();
const multer = require('multer');
const path = require('path');
const fs = require('fs').promises;
const File = require('../model/file');
const { v4: uuid4 } = require('uuid');
const mongoose = require('mongoose');
const { GridFsStorage } = require('multer-gridfs-storage');

// Configure GridFS Storage
const storage = new GridFsStorage({
    url: process.env.MONGO_CONNETION_URL,
    options: { useNewUrlParser: true, useUnifiedTopology: true },
    file: (req, file) => {
        return new Promise((resolve, reject) => {
            const filename = `${Date.now()}-${Math.round(Math.random() * 1E9)}${path.extname(file.originalname)}`;
            const fileInfo = {
                filename: filename,
                bucketName: 'uploads' // This will create uploads.files and uploads.chunks collections
            };
            resolve(fileInfo);
        });
    }
});

let upload = multer({ storage, limits: { fileSize: 1000000 * 200 } }).single('file');

router.post('/', (req, res) => {
    // Set JSON content type
    res.setHeader('Content-Type', 'application/json');

    console.log('File upload started', {
        contentType: req.get('content-type'),
        bodySize: req.get('content-length')
    });

    //store file
    upload(req, res, async (err) => {
        if (err) {
            console.error('Upload error:', {
                message: err.message,
                code: err.code,
                field: err.field
            });
            return res.status(500).json({ error: err.message });
        }
        
        // validate request
        if (!req.file) {
            console.log('No file in request. Request body:', req.body);
            return res.json({ message: 'No file uploaded' });
        }

        console.log('File received:', {
            filename: req.file.filename,
            size: req.file.size,
            mimetype: req.file.mimetype,
            path: req.file.path
        });

        const uuid = uuid4();
        const pin = Math.floor(100000 + Math.random() * 900000).toString();

        try {
            console.log('File successfully uploaded to GridFS:', req.file.filename, 'ID:', req.file.id);

            // Store metadata into our traditional db to link it with our application logic (uuid, pin, etc.)
            const file = new File({
                filename: req.file.originalname, 
                uuid: uuid,
                gridFsId: req.file.id, // The ObjectID generated by GridFS
                size: req.file.size,
                pin: pin
            });

            console.log('Attempting to save file metadata to DB...');
            const response = await file.save();
            console.log('File metadata saved successfully:', {
                uuid: response.uuid,
                id: response._id,
                filename: response.filename
            });
            
            const fileUrl = `${process.env.APP_BASE_URL}/files/${response.uuid}`;
            const qrCodeDataUrl = await QRCode.toDataURL(fileUrl);
            console.log('Generated URL:', fileUrl);
            console.log('APP_BASE_URL:', process.env.APP_BASE_URL);
            
            return res.json({ 
                file: fileUrl,
                uuid: response.uuid, // Include UUID in response for email step
                pin: response.pin,
                qrCode: qrCodeDataUrl
            });
        } catch (error) {
            console.error('Error saving file metadata to DB:', {
                message: error.message,
                stack: error.stack,
                name: error.name
            });
            return res.status(500).json({ 
                error: 'Failed to save file metadata',
                details: error.message,
                name: error.name
            });
        }
    });
});


router.post('/send', async (req, res) => { 
    const { uuid, emailTo, emailFrom } = req.body;

    // validate request
    if (!uuid || !emailTo || !emailFrom) {
        return res.status(422).send({ error: 'All fields are required.' });
    }
    try {
        const file = await File.findOne({ uuid: uuid });
        if (!file) return res.status(404).send({ error: 'File not found.' });

        if (file.sender) {
            return res.status(422).send({ error: 'Email already sent once.' });
        }

        file.sender = emailFrom;
        file.receiver = emailTo;
        const response = await file.save();

        // send email (await and catch errors)
        const sendEmail = require('../services/emailService');
        await sendEmail({
            from: emailFrom,
            to: emailTo,
            subject: 'INShare File Sharing',
            text: `${emailFrom} shared a file with you.`,
            html: require('../services/emailTemplate')({
                emailFrom: emailFrom,
                downloadLink: `${process.env.APP_BASE_URL}/files/${file.uuid}`,
                size: (file.size / 1000).toFixed(2) + ' KB',
                expires: '24 hours'
            })
        });

        return res.send({ success: true });
    } catch (err) {
        console.error('Error in /api/files/send:', err);
        return res.status(500).send({ error: 'Internal server error' });
    }

})

router.get('/pin/:pin', async (req, res) => {
    try {
        const file = await File.findOne({ pin: req.params.pin });
        if (!file) {
            return res.status(404).json({ error: 'Invalid PIN' });
        }
        return res.json({ uuid: file.uuid });
    } catch (err) {
        return res.status(500).json({ error: 'Internal server error while looking up PIN' });
    }
});

module.exports = router;